name: Pull_Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack
              env:
                  WORKING_DIR: ./storageservice
         