name: Deployment

on:
  release:
    types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      build -c --skip-tests
              env:
                  BASE_URL: ${{ secrets.BASE_URL }}
                  SHARED_ACCESS_SIGNATURE: ${{ secrets.SHARED_ACCESS_SIGNATURE }}
                  ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
                  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
                  AUTHORIZATION_METHOD: ${{ secrets.AUTHORIZATION_METHOD }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      push
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
                  